version: '2'
services:
  app:
    container_name: ffsapi-app
    build: ./app/
    image: ffsapi-app
    ports:
      - '80:80'
    volumes:
      - ../:/var/www/app/
    tty: true
    depends_on:
      - db
      - redis
  db:
    container_name: ffsapi-mysql
    build: ./mysql/
    image: ffsapi-mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: app
    volumes:
      - ./mysql/db_data:/var/lib/mysql
  redis:
    container_name: ffsapi-redis
    image: "redis:latest"
    ports:
      - '6379:6379'
    volumes:
      - ./redis/db_data:/data
